// Command generate bakes a subset of a TrueType/OpenType font into
// glyphs.go for package font. It is run by hand (or via go:generate),
// never as part of a normal build:
//
//	go run ./render/svg/font/generate -ttf Inter-Regular.ttf -out render/svg/font/glyphs.go
//
// It emits each subset glyph's outline as an SVG path in font units in
// sfnt's native Y-down orientation (ascenders are negative Y, matching
// SVG), plus advance widths and the
// ascent/descent/em metrics. golang.org/x/image is a generator-only
// dependency; the runtime font package imports only the baked output.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"

	"golang.org/x/image/font"
	"golang.org/x/image/font/sfnt"
	"golang.org/x/image/math/fixed"
)

func main() {
	ttfPath := flag.String("ttf", "Inter-Regular.ttf", "path to the source TrueType/OpenType font")
	outPath := flag.String("out", "glyphs.go", "path to the generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*ttfPath)
	if err != nil {
		log.Fatalf("read font: %v", err)
	}
	f, err := sfnt.Parse(data)
	if err != nil {
		log.Fatalf("parse font: %v", err)
	}

	var b sfnt.Buffer
	// ppem in pixels == units-per-em yields coordinates and advances in
	// font units (so EmSize == UnitsPerEm matches the emitted geometry).
	em := fixed.I(int(f.UnitsPerEm()))

	metrics, err := f.Metrics(&b, em, font.HintingNone)
	if err != nil {
		log.Fatalf("metrics: %v", err)
	}

	runes := subset()
	type entry struct {
		r    rune
		path string
		adv  float64
	}
	var entries []entry
	for _, r := range runes {
		idx, err := f.GlyphIndex(&b, r)
		if err != nil || idx == 0 {
			continue // not in the font
		}
		segs, err := f.LoadGlyph(&b, idx, em, nil)
		if err != nil {
			continue
		}
		adv, err := f.GlyphAdvance(&b, idx, em, font.HintingNone)
		if err != nil {
			continue
		}
		entries = append(entries, entry{r: r, path: segmentsToPath(segs), adv: f2(adv)})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].r < entries[j].r })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by render/svg/font/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package font\n\n")
	fmt.Fprintf(&buf, "// Font metrics in em units.\n")
	fmt.Fprintf(&buf, "var (\n")
	fmt.Fprintf(&buf, "\tAscent  float64 = %s\n", num(f2(metrics.Ascent)))
	fmt.Fprintf(&buf, "\tDescent float64 = %s\n", num(f2(metrics.Descent)))
	fmt.Fprintf(&buf, "\tEmSize  float64 = %s\n", num(float64(f.UnitsPerEm())))
	fmt.Fprintf(&buf, ")\n\n")
	fmt.Fprintf(&buf, "// Glyphs maps a rune to its outline (SVG path, em units, Y-down) and advance.\n")
	fmt.Fprintf(&buf, "var Glyphs = map[rune]Glyph{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%s: {Path: %q, Advance: %s},\n", runeLit(e.r), e.path, num(e.adv))
	}
	fmt.Fprintf(&buf, "}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt generated source: %v", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", *outPath, err)
	}
	fmt.Printf("wrote %d glyphs to %s\n", len(entries), *outPath)
}

// subset is the bundled rune set: printable ASCII, the Latin-1
// supplement, and a few typographic punctuation marks.
func subset() []rune {
	var rs []rune
	for r := rune(0x20); r <= 0x7E; r++ {
		rs = append(rs, r)
	}
	for r := rune(0xA0); r <= 0xFF; r++ {
		rs = append(rs, r)
	}
	rs = append(rs, '–', '—', '‘', '’', '“', '”', '…')
	return rs
}

// segmentsToPath converts sfnt outline segments to an SVG path "d"
// string. Contours are closed with Z.
func segmentsToPath(segs []sfnt.Segment) string {
	var sb bytes.Buffer
	started := false
	for _, s := range segs {
		switch s.Op {
		case sfnt.SegmentOpMoveTo:
			if started {
				sb.WriteString("Z")
			}
			started = true
			fmt.Fprintf(&sb, "M%s %s", num(f2(s.Args[0].X)), num(f2(s.Args[0].Y)))
		case sfnt.SegmentOpLineTo:
			fmt.Fprintf(&sb, "L%s %s", num(f2(s.Args[0].X)), num(f2(s.Args[0].Y)))
		case sfnt.SegmentOpQuadTo:
			fmt.Fprintf(&sb, "Q%s %s %s %s",
				num(f2(s.Args[0].X)), num(f2(s.Args[0].Y)),
				num(f2(s.Args[1].X)), num(f2(s.Args[1].Y)))
		case sfnt.SegmentOpCubeTo:
			fmt.Fprintf(&sb, "C%s %s %s %s %s %s",
				num(f2(s.Args[0].X)), num(f2(s.Args[0].Y)),
				num(f2(s.Args[1].X)), num(f2(s.Args[1].Y)),
				num(f2(s.Args[2].X)), num(f2(s.Args[2].Y)))
		}
	}
	if started {
		sb.WriteString("Z")
	}
	return sb.String()
}

// f2 converts a 26.6 fixed-point value to float64.
func f2(v fixed.Int26_6) float64 { return float64(v) / 64 }

// num formats a float without a trailing exponent or redundant zeros.
func num(v float64) string { return strconv.FormatFloat(v, 'g', -1, 64) }

// runeLit renders a rune as a readable Go literal.
func runeLit(r rune) string {
	if r >= 0x20 && r < 0x7F && r != '\'' && r != '\\' {
		return "'" + string(r) + "'"
	}
	return fmt.Sprintf("0x%04X", r)
}
