package mermaid

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"testing"
)

// compatSample is one row of the published compatibility matrix: a named
// Mermaid feature, a minimal source exercising it, and the compatibility
// outcome it must classify as. Every Source here has been verified to
// classify reliably (single-feature samples); the matrix documents only what
// is tested, not aspirational coverage.
type compatSample struct {
	Feature string
	Source  string
	Want    Compat
}

// compatSamples is the source of truth for docs/mermaid-compatibility.md.
// Add a row here, run with UPDATE_COMPAT_MATRIX=1 to regenerate the doc.
var compatSamples = []compatSample{
	{"Flowchart (graph / flowchart)", "graph TD\n  A --> B\n", CompatFull},
	{"Flow directions (TD, LR, RL, BT)", "flowchart LR\n  A --> B\n", CompatFull},
	{"Labeled edges", "graph TD\n  A -->|yes| B\n", CompatFull},
	{"Node shapes (rect, round, circle)", "graph TD\n  A[rect] --> B(round)\n  B --> C((circle))\n", CompatFull},
	{"Decision / rhombus node", "graph TD\n  A{decision} --> B[ok]\n", CompatFull},
	{"Subgraphs", "graph TD\n  subgraph G\n    A --> B\n  end\n", CompatFull},
	{"Edge variants (dotted, thick)", "graph LR\n  A -.-> B\n  B ==> C\n", CompatFull},
	{"style directive", "graph TD\n  A --> B\n  style A fill:#f00\n", CompatStyleDropped},
	{"classDef + class", "graph TD\n  A --> B\n  classDef big fill:#f00\n  class A big\n", CompatStyleDropped},
	{"linkStyle directive", "graph LR\n  A --> B\n  linkStyle 0 stroke:#f00\n", CompatStyleDropped},
	{"click / interaction", "graph TD\n  A --> B\n  click A \"https://x\"\n", CompatStyleDropped},
	{"sequenceDiagram", "sequenceDiagram\n  A->>B: hi\n", CompatUnsupported},
	{"pie chart", "pie\n  \"a\" : 10\n", CompatUnsupported},
	{"gantt chart", "gantt\n  title X\n", CompatUnsupported},
}

// TestCompatSamples_Classify guards the matrix data: every documented sample
// must still classify as the matrix claims. A change in ingestion behavior
// that moves a sample to a different outcome fails here, forcing the matrix to
// be regenerated honestly.
func TestCompatSamples_Classify(t *testing.T) {
	for _, s := range compatSamples {
		t.Run(s.Feature, func(t *testing.T) {
			got, _ := Classify([]byte(s.Source))
			if got != s.Want {
				t.Errorf("Classify(%q) = %v, want %v (matrix is stale — re-verify and regenerate)", s.Source, got, s.Want)
			}
		})
	}
}

const compatMatrixPath = "../../docs/mermaid-compatibility.md"

// TestCompatMatrix_DocUpToDate keeps docs/mermaid-compatibility.md in lockstep
// with compatSamples + the classifier. It regenerates the matrix and fails if
// the committed doc differs — run `UPDATE_COMPAT_MATRIX=1 go test
// ./ingest/mermaid` to refresh it. Same self-maintaining philosophy as
// `sirena bake --check`.
func TestCompatMatrix_DocUpToDate(t *testing.T) {
	want := renderCompatMatrix()
	if os.Getenv("UPDATE_COMPAT_MATRIX") != "" {
		if err := os.WriteFile(compatMatrixPath, want, 0o644); err != nil {
			t.Fatalf("write matrix: %v", err)
		}
		t.Log("regenerated", compatMatrixPath)
		return
	}
	got, err := os.ReadFile(compatMatrixPath)
	if err != nil {
		t.Fatalf("read %s: %v (run UPDATE_COMPAT_MATRIX=1 go test ./ingest/mermaid to generate)", compatMatrixPath, err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale; run UPDATE_COMPAT_MATRIX=1 go test ./ingest/mermaid to regenerate", compatMatrixPath)
	}
}

// renderCompatMatrix builds the full matrix document deterministically from
// compatSamples by classifying each sample live (so the doc can never claim an
// outcome the classifier disagrees with).
func renderCompatMatrix() []byte {
	var b strings.Builder
	b.WriteString("# Mermaid → Sirena compatibility matrix\n\n")
	b.WriteString("<!-- Generated by `go test ./ingest/mermaid` (TestCompatMatrix_DocUpToDate).\n")
	b.WriteString("     Do not edit by hand — change compatSamples in compat_matrix_test.go and run\n")
	b.WriteString("     `UPDATE_COMPAT_MATRIX=1 go test ./ingest/mermaid` to regenerate. -->\n\n")
	b.WriteString("Sirena ingests Mermaid **flowcharts** (`graph` / `flowchart`) into its typed IR\n")
	b.WriteString("and renders them to deterministic SVG. This matrix classifies how representative\n")
	b.WriteString("Mermaid features survive that ingestion.\n\n")
	b.WriteString("**This is a structural-fidelity matrix, not a pixel-parity claim.** Sirena applies\n")
	b.WriteString("its own layout and theme; output never aims to match Mermaid's pixels.\n\n")
	b.WriteString("Outcomes:\n\n")
	b.WriteString("- **full** — every node and edge is represented; no diagnostics.\n")
	b.WriteString("- **styling-dropped** — geometry survives; styling directives (`style`, `classDef`,\n")
	b.WriteString("  `linkStyle`, `click`) have no sirena equivalent and are dropped.\n")
	b.WriteString("- **partial** — the flowchart renders but some statements were dropped (parse errors\n")
	b.WriteString("  or unsupported statement types). Rare: malformed input usually classifies as\n")
	b.WriteString("  *unsupported* instead, because the flowchart node fails to parse at all.\n")
	b.WriteString("- **unsupported** — nothing renders; the input is not a flowchart (e.g.\n")
	b.WriteString("  `sequenceDiagram`, `pie`, `gantt`).\n\n")
	b.WriteString("| Feature | Sample | Outcome |\n")
	b.WriteString("|---|---|---|\n")
	for _, s := range compatSamples {
		got, _ := Classify([]byte(s.Source))
		b.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", s.Feature, oneLineSample(s.Source), got))
	}
	b.WriteString("\nThis matrix reflects the tested samples in `compat_matrix_test.go`; it is\n")
	b.WriteString("representative, not exhaustive. The classifier behind it is `mermaid.Classify`.\n")
	return []byte(b.String())
}

// oneLineSample collapses a multi-line Mermaid source into a single backtick-
// safe table cell: newlines become "; " and pipes are escaped so they do not
// break the Markdown table column.
func oneLineSample(src string) string {
	lines := strings.Split(strings.TrimSpace(src), "\n")
	for i, ln := range lines {
		lines[i] = strings.TrimSpace(ln)
	}
	joined := strings.Join(lines, "; ")
	return strings.ReplaceAll(joined, "|", "\\|")
}
